sonar.organization=kunal-yelgate
sonar.projectKey=kunal-yelgate_SerpApi-project
sonar.sources=backend,frontend/src
sonar.tests=backend/tests
sonar.exclusions=backend/tests/**,frontend/src/**/*.test.js,frontend/src/**/*.test.jsx
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
